const words = [
    "EMPTY", "NULL", "BLANK", "MISSING", "FADING", "DARKNESS", "HOLLOW", "ECHO", "WASTELAND", 
    "SHADOW", "GAP", "VACUUM", "ABYSS", "UNSEEN", "DISAPPEAR", "MYSTERY", "CIPHER", "EMPTYNESS", 
    "SILENCE", "SPECTRE", "GHOST", "INVISIBLE", "STILLNESS", "INCOMPLETENESS", "HUSH", "DIM", "SUSPENSE", 
    "UNDEFINED", "ILLUSION", "PHANTOM", "HORIZON", "FORGOTTEN", "NEBULA", "DISTANT", "AFTERGLOW", "OBSCURED", 
    "LOST", "INFINITE", "CLOUD", "VANISHING", "CLOUDLESS", "WHISPER", "ECLIPSE", "UNKNOWABLE", "ABANDON", 
    "OUTSIDE", "FADING", "ECHOES", "MIST", "ENDLESS", "COLLAPSE", "MIRAGE", "EXTINCTION", "TIMESLIP", 
    "FADE", "REMNANT", "RAVAGE", "DEPARTURE", "VANISH", "NEBULOUS", "DIMENSION", "HORIZON", "FORSAKEN", 
    "HORIZONLESS", "DEVOID", "DARK", "WASTED", "VOIDSPACE", "TIMELESS", "SLEEP", "SUBLIME", "FORGONE", 
    "ECLIPSING", "TRANQUIL", "UNHEARD", "BLEAK", "FROSTED", "DISPLACED", "ABSENT", "UNREVEALED", 
    "SHROUDED", "NARROW", "INVISIBLE", "BLOODLESS", "COLD", "VANQUISH", "AETHER", "SUSPENDED", 
    "UNTOUCHED", "SHRUNKEN", "FRAGMENTED", "TRANSIENT", "IMPACT", "LIMBO", "AFTERSHOCK", "EXILE", 
    "ELECTRIC", "EMPTYFIELD", "FROST", "CHASM", "UNEXPLORED", "QUANTUM", "SUBMERGED", "LOSTSPACE", 
    "VANISHED", "UNFATHOMABLE", "INVISIBLE", "PERSISTENT", "UNTOUCHED", "EERIE", "SLEEPLESS", "STAGNANT", 
    "FADINGAWAY", "OBLIVION", "UNREACHABLE", "FORSAKEN", "SEVERED", "DIMNESS", "COLDNESS", "INSUBSTANTIAL", 
    "UNTOUCHED", "IMPERCEPTIBLE", "UNVISIBLE", "CRUMBLING", "EVAPORATING", "FADINGLIGHT", "INVISIBLEFORCE", 
    "GRIM", "UNHEARDOF", "AETHERIAL", "PERSISTENT", "LUMINOUS", "LOSTTIME", "LOSTSPACES", "FORGOTTEN", 
    "CHAOTIC", "NIGHTFALL", "STILLNESS", "AETHER", "OBSCURED", "UNDISCOVERED", "NEGATIVE", "FORGOTTENREALMS", 
    "IMPACTFUL", "ENDURING", "BEREFT", "DISCONNECTED", "VANISHINGPOINT", "UNTOUCHABLE", "HAUNTED", 
    "NUMBING", "TRANQUILITY", "MELANCHOLIC", "DISILLUSION", "VOIDLIGHT", "AGONY", "BLEACHED", "OBLITERATED", 
    "DIMMING", "TRANSPARENT", "SHRUNK", "VANISHINGACT", "ENIGMATIC", "UNCERTAIN", "DIMENSIONLESS", 
    "FROSTBITTEN", "OBSOLETE", "EVAPORATED", "VACANT", "BLEAKNESS", "GLOWING", "SLEEPY", "VACUUMED", 
    "DEPLETED", "RETRACTED", "UNFELT", "SKELETAL", "SHATTERED", "DISSIPATED", "FORGOTTEN", "RELINQUISHED", 
    "DUST", "DISCONNECTED", "DISSOLVING", "TIDAL", "FADINGRAYS", "WASTELAND", "WASTED", "DIMMINGOUT", 
    "GLASSY", "PALE", "UNFINISHED", "NOISELESS", "FADINGAWAY", "FEATHER", "SINGULARITY", "UNHEARD", 
    "AFTERGLOW", "INVISIBLEWORLD", "INTERSTELLAR", "HORIZONLESS", "UNSOLVED", "HALFSEEN", "EXTERNAL", 
    "TRAGIC", "STAGNATED", "EMPTINESS", "EVAPORATE", "DIMMING", "FADING", "VANISHINGPOINT", "GRAVE", 
    "SUSPENDED", "ETHEREAL", "DISTANTHORIZON", "AFTERSHOCK", "INSUBSTANTIAL", "DRIFTING", "NONEXISTENT", 
    "QUASI", "TRANSLUCENT", "OBLIVIOUS", "DARKNESS", "LURKING", "FADINGTIME", "UNDETECTED", "FORGONE", 
    "COLLAPSING", "SILENT", "EMPTYSPACE", "TIMELESSNESS", "INVISIBLEFORCE", "VACANTLIGHT", "DISPLACED", 
    "EXCLUSIVE", "VANISHINGWORLD", "NOTHEARD", "DEVOID", "EXISTENTIAL", "DARKSPACE", "UNFELT", "MINIMAL", 
    "HOLLOWED", "EXTINCT", "UNHEARD", "INFRARED", "UNSEEN", "CONCEALED", "DEADZONE", "HORIZONGONE", 
    "EMPTYVOID", "TRANSLUCENT", "BLOODLESS", "LOSTINTHEDARK", "SHROUDED", "VACANTVASTNESS", "DIMLIGHT", 
    "ETHEREALSPACE", "UNHEARDOF", "INVISIBLEGLOW", "SOULLESS", "DARKNESSUNSEEN", "FORGOTTENLOST", "DARKSKY", 
    "TAR", "INVISIBLEWAVE", "MYSTERY", "SILENCED", "SHROUDED", "STILLNESS", "DIMVISION", "FADINGECHO", 
    "UNTOUCHEDSPACE", "HIDDEN", "EXILE", "UNKNOWABLE", "DEATH", "SOLO", "UNREVEALED", "FORGOTTENWAVES", 
    "UNDISCOVEREDSPACE", "VOIDPOINT", "INVISIBLEAIR", "MELANCHOLY", "FADINGDREAM", "SOUL", "OBLIVIOUS", 
    "REMOVED", "WASTED", "TRANSLUCENCY", "DIMSTARDOM", "LOSTLIGHT", "UNFELT", "FORSAKEN", "FADINGGLOW", 
    "CLOUDLESS", "UNHEARDOF", "LURKING", "UNTOUCHABLE", "TRANSITIONAL", "VANISHEDLIGHT", "COLLAPSINGVOID", 
    "TRANSLUCENTGLOW", "DEEPUNSPOKEN", "SECLUDED", "UNDISCOVERABLE", "FADINGGLITTER", "EXTINCT", "UNHEARD", 
    "GRADUAL", "GONE", "VANISHINGLIGHT", "STILL", "DIMLIGHT", "UNOBTAINABLE", "DARKWATERS", "TENTATIVE", 
    "IMAGINED", "UNSEENHORIZON", "DISAPPEARED", "DARKNESSHOVER", "INVISIBLEEXISTENCE", "FORGOTTENSPACE", 
    "INVISIBLEWAVES", "FADINGEND", "COLLAPSINGWORLD", "MISSING", "CLOSE", "MINIMALSPACE", "EMPTYNESS", 
    "LIGHTWITHOUT", "UNTOUCHABLEFORCE", "UNREVEALEDREALM", "NODIRECTION", "INVISIBLETIDE", "LOSTINTHEDEEP", 
    "FORGOTTENFOREST", "DISTANTLIGHT", "THEFORGOTTEN", "UNSEENBEYOND", "DISTANTSHADOWS", "ISOLATED", 
    "FADED", "DARKSEEP", "LOSTECHO", "TIMESHIFT", "EMPTYVOIDSPACE", "PHANTOMSPACE", "MELANCHOLICVOID"
  ];
  
  function generateWord() {
    const previousWord = document.getElementById("generated-text").textContent;
    let newWord;
  
    do {
      newWord = words[Math.floor(Math.random() * words.length)];
    } while (newWord === previousWord);
  
    document.getElementById("generated-text").textContent = newWord;
  }
  